version: '3.7'
services:
  app:
    container_name: go-chat-app
    build:
      context: ./src
      dockerfile: ./Dockerfile.local
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./src/:/workspace
      - ./go:/go
    depends_on:
      - "db"
    env_file:
      - ./.env
    environment:
      MYSQL_HOST: 'db'
      MYSQL_PORT: '3306'
    command: air -c ".air.toml"
  db:
    container_name: go-chat-db
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: 'pw'
      TZ: 'Asia/Tokyo'
    volumes:
    - ./db_data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci


