version: '3.7'
services:
  app:
    container_name: jwt-issuer-app
    build:
      context: .
      dockerfile: ./Dockerfile.local
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./src/:/workspace
      - ./go:/go
      - ./local_id_rsa:/secret/id_rsa
    depends_on:
      - "db"
    environment:
      DB_HOST: 'db'
      DB_PORT: '3306'
    command: air -c ".air.toml"
  db:
    container_name: jwt-db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'dmc'
      TZ: 'Asia/Tokyo'
    volumes:
    - ./db_data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci


