FROM golang:1.17-alpine3.14
WORKDIR /workspace

ARG UID=1000
ARG USER=docker_user

COPY ./go.mod ./go.sum ./
RUN apk update \
  && apk add --no-cache make \
  # air
  gcc \
  && go mod download

RUN adduser --uid $UID --disabled-password $USER && chmod -R 700 /workspace
USER $USER
